@startuml

class Beverage{
    -String name
    -double price
    -double alcPercent
    -double sizeInCL
    + Beverage()

}

class Cafe{
    -String name
    -ArrayList<Beverage> menu
    +Cafe()
    +void addItem()
    +void showMen()
    +String toString()
}

Cafe *-- Beverage : has
@enduml